base:
  accessToken: 27482-71b3313c-0e88-481b-8c93-0e465ab8a868
  fileKey: ZvsRf99Ik11qS4PjS6MAFc

colors:
  includingNodes:
    - 7:24
  destinationPath: FigmaGenDemo/Generated/Colors.swift
  templatePath: Templates/Colors.stencil

textStyles:
  includingNodes:
    - 3:19
  destinationPath: FigmaGenDemo/Generated/TextStyle.swift
  templatePath: Templates/TextStyles.stencil
